### PR TITLE
Gin

### PR DESCRIPTION
**Pull request by jonaz**
Move from martini to gin. Websocket stuff has been rewritten. Everything else is pretty straight forward.

Ongoing work! 
Please dont merge yet. But test it with the webgui!

### CODE REVIEW

**Comment by stamp** [comment]
I'm running your changes now and everything seems to work just fine. Will continue to test run for a couple of days because our previous websocket issues :p

**Comment by stamp** [comment]
I had to revert to a pre-gin version (6609cceb54db10782972ff02cdc5e99d71c92151) beacuse http rest commands do not work. Have not had time to trace the issue yet.

**Comment by jonaz** [comment]
I did test them on gin branch using simple node and it 

http://localhost:8080/api/nodes/simple/cmd/on/2

results in this in simple node logs:

2015-08-28 12:52:55 Info - main.go:159 - Incoming command from server: protocol.Command{Ping:false, Cmd:"", Args:[]string{"on", "2"}, Params:[]string(nil)}


I think its correct?

**Comment by jonaz** [comment]
Never mind. It was not correct. I have now fixed the issue in: 6038febe81b6f06048a1d7f0892aff8d951db9ca

**Comment by stamp** [comment]
Tested and works fine :)

**Pull request merged**
