### PR TITLE
Refactored the special server node out of nodeserver into own packet

### PR DESCRIPTION
**Pull request by jonaz**
Now its easier to write tests for both nodeserver and servernode.
We have cleaner code. 

To solve this i introduced the serverprotocol Node interface. 
We might move that to the "base" protocol later if this works fine. 

Tip in the future: always think behavior and use interfaces. Its even possible to compose bigger interfaces from smaller ones.

### CODE REVIEW

**Comment by jonaz** [comment]
FYI coveralls is down to thats why the travis-ci tests fail when they try to post coverage there.

**Comment by jonaz** [comment]
I have tested everything except Kibana logger

**Comment by stamp** [comment]
I think you have forgot to add the servernode folder to the commit. I cant compile the code :/

**Comment by stamp** [comment]
The travis failure was 
> imports github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/servernode: cannot find package "github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/servernode"

**Comment by jonaz** [comment]
yeah i forgot to add servernode. It has now been added!

**Pull request merged**
